<?php

namespace AppBundle\Repository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
    //public function getAllThemes(){
        // 't' pour allias theme
        //$qb = $this->createQueryBuilder( 't');
        //$qb->select("t.id, UPPER(t.name) as name");

        public function getAllThemes(){
        // 't' pour allias theme
        $qb = $this->createQueryBuilder( 't');
        $qb->select("t.name, count(p.id) as numberOfPosts, t.id")

        ->innerJoin("t.posts",  "p")
        ->groupBy("t.id");

        dump($qb->getDQL());
        return $qb->getQuery();
    }
}
