# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.service.hello_renderer:
        class: AppBundle\Service\HelloRenderer

    service.hello:
      class: AppBundle\Service\HelloService
      arguments:
        - "world"
        - "@app.service.hello_renderer"
      shared: false

    post.manager:
      class: AppBundle\Entity\Manager\PostManager
      arguments:
        - "@doctrine"